[package]
name = "axum-oidc"
description = "A wrapper for the openidconnect crate for axum"
version = "0.1.2"
edition = "2021"
authors = [ "Paul Z <info@pfz4.de>" ]
readme = "README.md"
repository = "https://github.com/pfz4/axum-oidc"
license = "LGPL-3.0-or-later"
keywords = [ "axum", "oidc", "openidconnect", "authentication" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.50"
axum-core = "0.3"
axum = { version = "0.6", default-features = false, features = [ "query" ] }
tower-service = "0.3.2"
tower-layer = "0.3.2"
tower-sessions = { version = "0.4", default-features = false, features = [ "axum-core" ] }
http = "0.2"
async-trait = "0.1"
openidconnect = "3.4"
serde = "1.0"
futures-util = "0.3"
reqwest = { version = "0.11", default-features = false }
